apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: spire-agent
  namespace: spire
  labels:
    app: spire-agent
spec:
  selector:
    matchLabels:
      app: spire-agent
  template:
    metadata:
      labels:
        app: spire-agent
    spec:
      serviceAccountName: spire-agent
      containers:
      - name: spire-agent
        image: ghcr.io/spiffe/spire-agent:1.5.0
        args: ["-config", "/run/spire/config/agent.conf"]
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        ports:
        - containerPort: 8080
          name: health
        - containerPort: 9091
          name: metrics
        volumeMounts:
        - name: spire-config
          mountPath: /run/spire/config
          readOnly: true
        - name: spire-data
          mountPath: /run/spire/data
        - name: spire-secrets
          mountPath: /run/spire/secrets
          readOnly: true
        - name: spire-sockets
          mountPath: /run/spire/sockets
        - name: kubelet-socket
          mountPath: /var/run/kubernetes
          readOnly: true
        livenessProbe:
          httpGet:
            path: /live
            port: health
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: health
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          fsGroup: 1000
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      volumes:
      - name: spire-config
        configMap:
          name: spire-agent
      - name: spire-data
        emptyDir: {}
      - name: spire-secrets
        secret:
          secretName: spire-agent-secrets
      - name: spire-sockets
        hostPath:
          path: /run/spire/sockets
          type: DirectoryOrCreate
      - name: kubelet-socket
        hostPath:
          path: /var/run/kubernetes
          type: Directory
      securityContext:
        fsGroup: 1000 