# SPIRE Server Deployment
# This file defines the Kubernetes deployment for the SPIRE server.
# The SPIRE server is the central authority for workload identity in the cluster.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: spire-server
  namespace: spire
  labels:
    app: spire-server
spec:
  # Number of server replicas
  # For production, consider running multiple replicas for high availability
  # Optional improvement: Increase replicas to 3 for high availability
  # Rationale: Ensures service availability during node failures or updates
  replicas: 1

  # Optional improvement: Limit the number of old ReplicaSets to retain
  # Rationale: Prevents excessive storage usage and simplifies rollback management
  # Default: 10 (adjust based on your rollback needs)
  revisionHistoryLimit: 10

  # Optional improvement: Deployment strategy for controlled updates
  # Rationale: Ensures zero-downtime updates and controlled rollback
  # maxUnavailable: Maximum number of pods that can be unavailable during update
  # maxSurge: Maximum number of pods that can be created above desired replicas
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

  selector:
    matchLabels:
      app: spire-server
  template:
    metadata:
      labels:
        app: spire-server
    spec:
      # Service account for the SPIRE server
      # This service account must have the necessary RBAC permissions
      serviceAccountName: spire-server

      # Optional improvement: Grace period for pod termination
      # Rationale: Allows time for in-flight requests to complete
      # Default: 30 seconds (adjust based on your workload)
      terminationGracePeriodSeconds: 30

      containers:
      - name: spire-server
        # SPIRE server container image
        # Use a specific version tag for production deployments
        image: ghcr.io/spiffe/spire-server:1.5.0

        # Optional improvement: Always pull the image
        # Rationale: Ensures latest security patches are applied
        # Note: May increase deployment time
        imagePullPolicy: Always

        # Command line arguments
        # Points to the server configuration file
        args: ["-config", "/run/spire/config/server.conf"]

        ports:
        # SPIRE server API port
        # Used for agent-server communication
        - containerPort: 8081
          name: spire-server

        # Health check port
        # Used for liveness and readiness probes
        - containerPort: 8080
          name: health

        # Metrics port
        # Used for Prometheus metrics collection
        - containerPort: 9091
          name: metrics

        volumeMounts:
        # Configuration volume
        # Mounts the server configuration
        - name: spire-config
          mountPath: /run/spire/config
          readOnly: true

        # Data volume
        # Stores persistent data like the datastore
        # Optional improvement: Use PersistentVolume for production
        # Rationale: Ensures data persistence across pod restarts
        - name: spire-data
          mountPath: /run/spire/data

        # Secrets volume
        # Mounts sensitive data like keys and certificates
        - name: spire-secrets
          mountPath: /run/spire/secrets
          readOnly: true

        # Sockets volume
        # Used for Unix domain socket communication
        - name: spire-sockets
          mountPath: /run/spire/sockets

        # Optional improvement: Startup probe
        # Rationale: Better handling of slow-starting containers
        # Prevents premature restarts during initialization
        startupProbe:
          httpGet:
            path: /live
            port: health
          failureThreshold: 30
          periodSeconds: 10

        # Liveness probe
        # Ensures the container is running properly
        # Optional improvement: Added timeout and failure threshold
        # Rationale: Better handling of temporary network issues
        livenessProbe:
          httpGet:
            path: /live
            port: health
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3

        # Readiness probe
        # Ensures the container is ready to handle requests
        # Optional improvement: Added timeout and failure threshold
        # Rationale: Better handling of temporary network issues
        readinessProbe:
          httpGet:
            path: /ready
            port: health
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3

        # Resource requirements
        # Adjust based on your workload and cluster capacity
        # Optional improvement: Monitor and adjust these values
        # Rationale: Prevents resource starvation and ensures performance
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi

        # Security context
        # Implements security best practices
        # Required: These settings are mandatory for security
        securityContext:
          # Run as non-root user
          runAsUser: 1000
          runAsGroup: 1000
          fsGroup: 1000
          # Read-only root filesystem
          readOnlyRootFilesystem: true
          # Prevent privilege escalation
          allowPrivilegeEscalation: false
          # Drop all capabilities
          capabilities:
            drop:
            - ALL

      volumes:
      # Configuration volume from ConfigMap
      - name: spire-config
        configMap:
          name: spire-server

      # Empty directory for persistent data
      # Optional improvement: Use PersistentVolume for production
      # Rationale: Ensures data persistence across pod restarts
      - name: spire-data
        emptyDir: {}

      # Secrets volume
      # Contains sensitive data like keys and certificates
      - name: spire-secrets
        secret:
          secretName: spire-server-secrets

      # Empty directory for Unix domain sockets
      - name: spire-sockets
        emptyDir: {}

      # Pod security context
      # Sets the filesystem group
      # Required: This setting is mandatory for security
      securityContext:
        fsGroup: 1000 