apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: your-registry/backend-image
        command: ["/bin/sleep", "infinity"]
        volumeMounts:
        - name: spire-agent-socket
          mountPath: /run/spire/sockets
        - name: spiffe-helper-config
          mountPath: /run/spire/config
      volumes:
      - name: spire-agent-socket
        hostPath:
          path: /run/spire/sockets
          type: Directory
      - name: spiffe-helper-config
        configMap:
          name: spiffe-sidecar-config
