apiVersion: v1
kind: ConfigMap
metadata:
  name: spiffe-sidecar-config
data:
  sidecar-config.json: |
    {
      "cmd": "",
      "cmd_args": [],
      "workload_api_socket": "/run/spire/sockets/agent.sock",
      "svid_file": "/tmp/svid.pem",
      "key_file": "/tmp/key.pem",
      "bundle_file": "/tmp/bundle.pem",
      "log_level": "DEBUG",
      "log_file": "/dev/stderr"
    }
