# Service Accounts Configuration
# This file defines service accounts for workload identity
# Note: This is a basic configuration. Production environments need more specific permissions.
#
# Cloud Provider Integration:
# - GCP: Use 'iam.gke.io/gcp-service-account' annotation
# - AWS: Use 'eks.amazonaws.com/role-arn' annotation
# - Azure: Use 'azure.workload.identity/client-id' annotation (with Azure AD Workload Identity)

apiVersion: v1
kind: ServiceAccount
metadata:
  # Required: Unique name for the service account
  name: workload-identity-sa
  # Required: Namespace where the service account will be created
  namespace: default
  annotations:
    # --- GCP Example ---
    # Required for GCP: Maps the Kubernetes service account to a GCP service account
    # Optional for other cloud providers: Remove or replace with provider-specific annotation
    iam.gke.io/gcp-service-account: "workload-identity@project.iam.gserviceaccount.com"
    # --- AWS Example ---
    # Required for AWS: Maps the Kubernetes service account to an AWS IAM role
    # eks.amazonaws.com/role-arn: "arn:aws:iam::123456789012:role/WorkloadIdentityRole"
    # --- Azure Example ---
    # Required for Azure: Maps the Kubernetes service account to an Azure AD application client ID
    # azure.workload.identity/client-id: "<azure-ad-app-client-id>"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  # Required: Unique name for the role
  name: workload-identity-role
  # Required: Namespace where the role will be created
  namespace: default
rules:
# Required: Define the permissions for the role
# Modify these based on your workload's needs
- apiGroups: [""]
  resources: ["pods", "services"]
  # Required: Define allowed actions
  # Optional: Add more verbs like "create", "update", "delete" if needed
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  # Required: Unique name for the role binding
  name: workload-identity-rolebinding
  # Required: Namespace where the binding will be created
  namespace: default
subjects:
# Required: Define which service account gets the role
- kind: ServiceAccount
  # Required: Must match the service account name defined above
  name: workload-identity-sa
  # Required: Must match the service account namespace
  namespace: default
roleRef:
  # Required: Reference to the role being bound
  kind: Role
  # Required: Must match the role name defined above
  name: workload-identity-role
  # Required: API group for the role
  apiGroup: rbac.authorization.k8s.io

# Production Environment Recommendations:
# Required:
# - Implement least privilege principle
# - Add namespace-specific roles
# - Include audit logging
# - Add more granular access controls
#
# Optional but Recommended:
# - Add labels for better resource management
# - Include annotations for documentation
# - Add resource quotas
# - Implement network policies
# - Add security context constraints 