# Service Accounts Configuration
# This file defines service accounts for workload identity
# Note: This is a basic configuration. Production environments need more specific permissions.

apiVersion: v1
kind: ServiceAccount
metadata:
  name: workload-identity-sa
  namespace: default
  annotations:
    iam.gke.io/gcp-service-account: "workload-identity@project.iam.gserviceaccount.com"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: workload-identity-role
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workload-identity-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: workload-identity-sa
  namespace: default
roleRef:
  kind: Role
  name: workload-identity-role
  apiGroup: rbac.authorization.k8s.io

# Note: This is a basic service account configuration. Production environments should:
# - Use more specific permissions
# - Implement least privilege principle
# - Add namespace-specific roles
# - Include audit logging
# - Add more granular access controls 